# -*- coding: utf-8 -*-
"""Python_Knee_Image_Transformations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WEVbwgrUYNpCC9MZgF_TMt5a-CsoaS-N
"""

# Commented out IPython magic to ensure Python compatibility.
!kaggle datasets download -d salikhussaini49/tcia-chest-ct; unzip tcia-chest-ct.zip; rm tcia-chest-ct.zip
# %cd TCIA\ Chest\ CT\ \(Sample\)

import imageio as iio
import matplotlib.pyplot as plt

# Read single DICOM image with imread
#im = iio.imread('chest-220.dcm')
im = iio.imread('22040')
# Plot three versions of dcm with image transformations
plt.rcParams['figure.figsize'] = (14, 8)
fig, axes = plt.subplots(nrows= 1, ncols= 3)
axes[0].imshow(im, cmap= 'gray')
axes[1].imshow(im, vmin= -200, vmax= 200, cmap= 'gray')
axes[2].imshow(im, vmin= -200, vmax= 200, cmap= 'magma')
axes[0].set_title('Original')
axes[1].set_title('High Contrast')
axes[2].set_title('Colored')
for ax in axes:
  ax.axis('off')
plt.show()